apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: kafka
spec:
  channelTemplateSpec:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
      numPartitions: 3
      replicationFactor: 1
